### ISSUE TITLE
Don't Hire Scott Barnes

### ISSUE THREAD

**Issue by bondiejack** [Microsoft/xaml-standard#134]
Anyone that creates a smurf account with to post about their glory days and stir up drama in a community should just stay gone. #97

**Comment by mossyblog** [comment]
whats a smurf account?

**Comment by Mike-EEE** [comment]
![image](https://cloud.githubusercontent.com/assets/2931376/26275337/f83e95e6-3d2b-11e7-9bd4-f2d2ad9ec304.png)

**Comment by birbilis** [comment]
Guess you can close this issue now too, discussion at the other one was interesting nevertheless

**Comment by mossyblog** [comment]
Well this is me tapping out. I used Unity3D daily now and made a conscious choice to step away from MS Community in 2010 because of the immaturity .. 

Its really down to you guys in the end. XAML Standard is your one and only chance to hold Microsoft accountable to some actionable change as it forces the entire UX Pipeline to adhere to an agreed contract - no more ducking / weaving away from "coming soon" narratives. As the moment they come up short they can't say "XAML 1.0 standard compliant" which is will be a sore point.

Right now they're on target to wiggle out of that responsibility and you ass hats are too busy attacking me to notice. 

Personally I ship faster, less cost and more device reach with Unity3D than with Microsoft products. Only time I use MS now is for Azure/Visual Studio.. the rest all funnels via Unity3d.

So... good luck. I'm out.

**Comment by Mike-EEE** [comment]
> Well this is me tapping out

Dang dude that wasn't much of a fight _at all_!  Sure you don't want to wait for them to close down this thread, first? 😆 😆 😆 🎉

**Comment by mossyblog** [comment]
:) nah,

Too busy for this nonsense and i know how it ends..

**Comment by jassmith** [comment]
Okay I think we clearly need some kind of policy about issues talking about individuals by name. Closing and locking...
