### ISSUE TITLE
Fluent Design System

### ISSUE THREAD

**Issue by MaherJendoubi** [Microsoft/xaml-standard#136]
Controls should be designed with respect of the Fluent Design System principles :
* Light
* Depth
* Motion
* Material
* Scale

**Comment by insinfo** [comment]
@MaherJendoubi
Since this would look like syntax, write an example.
I think this is more of an implementation detail than custom controls or UIKit controls properties. So what you want to say is the inclusion of a primitive property in the class FrameworkElement called "ZIndex" or something like this:

```xaml
<Button ZIndex="50" />
```

In order for the implementation of this standard XAML to be made a GPU accelerated render engine that interprets the ZIndex as depth

This may enter the XAML Standard Specification as a property of the controls, which would be wrapped from a primitive abstract class.

Or a reference implementation of the XAML Standard 1.0 Specification

**Comment by h82258652** [comment]
Fluent design is a platform feature, it should not be in xaml standard.

**Comment by MovGP0** [comment]
The design should depend on the platform. So [Material Design](https://material.io/) on Android, [Fluent Design](http://fluent.microsoft.com/) on Windows 10 devices, [Human Interface](https://developer.apple.com/ios/human-interface-guidelines/overview/design-principles/) on iOS, the [Tizon Design Prinziples](https://developer.tizen.org/design/mobile/design-principles) on Tizen, etc.

**Comment by harinikmsft** [comment]
As @h82258652 and @MovGP0 have already commented, XAML Standard is a vocabulary spec and does not get into very specific platform specific functionality or implementation details. XAML Standard implemented by UWP will automatically have the Windows 10 personality which includes Fluent design principles. Similarly, XAML Standard implemented by Xamarin.Forms targeting Android will honor material design principles. etc.,

**Comment by birbilis** [comment]
Will the user be able to affect them via platform specific properties though? (see related issue)

**Comment by harinikmsft** [comment]
To start with, you can use platform specific controls directly to affect platform specific properties. We are considering more fine tuning in terms of platform specific properties in the future, so perhaps there will be mechanisms for that in the future versions...
