### ISSUE TITLE
Adopt 3D world environment like Material Design from google

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [Microsoft/xaml-standard#137]
https://material.io/guidelines/material-design/environment.html

**Comment by Odonno** [comment]
Each design guidelines should be kept separated from the Standard implementation. So, Fluent Design and Material Design should not be a part of XAML Standard but more as an extension of it (XAML Material Standard?).

**Comment by mdtauk** [comment]
Z-Depth with a drop shadow element.  Cameras, Lights.  These could all be XAML elements which can be handled by a platform's renderer.  So on Android the XAML renderer would apply those things to Material Design.  UWP Fluent, and iOS well whatever iOS calls it's UI design.  Those three platforms have or will have the concept of layering so XAML should also include these notions

**Comment by insinfo** [comment]
Since this would look like syntax, write an example.
I think this is more of an implementation detail than custom controls or UIKit controls properties. So what you want to say is the inclusion of a primitive property in the class FrameworkElement called "ZIndex" or something like this:

```xaml
<Button ZIndex="50" />
```

In order for the implementation of this standard XAML to be made a GPU accelerated render engine that interprets the ZIndex as depth

This may enter the XAML Standard Specification as a property of the controls, which would be wrapped from a primitive abstract class.

Or a reference implementation of the XAML Standard 1.0 Specification

**Comment by mdtauk** [comment]
@insinfo  Just thinking out loud...
```
<!-- ZDepth has an int value -->

<!-- DropShadowMode is an enum which affects the type of shadow generated in reference to a page's light
     AmbientLight a soft shadow surrounding the object
     DirectLight a harsher shadow in relation to the position of the light -->

<Button Content="Button" 
        ZDepth="{StaticResource ControlLevelDepth}"
        DropShadowMode="AmbientLight"
        DropShadowColor="{ThemeResource SystemColourShadow}">
</Button>

```              `

**Comment by insinfo** [comment]
I understood then the properties "DropShadowMode", "DropShadowColor" and "ZDepth" are properties that have this in the primitive class of the specification and the enum "AmbientLight" "DirectLight". I think this has to be well detailed so that you can make a proposal to enter the specification. Undoubtedly is very interesting, but I think this can make the implementation much more complex, especially in rendering egine.

**Comment by harinikmsft** [comment]
XAML Standard is a vocabulary spec and does not get into very specific platform specific functionality or implementation details. XAML Standard implemented by UWP will automatically have the Windows 10 personality which includes Fluent design principles. Similarly, XAML Standard implemented by Xamarin.Forms targeting Android will honor material design principles. etc.,

Moreover, to start with XAML Standard has to apply to as wide a range of platforms as possible. So, introducing zDepth is too specific for a first version. If you would like to see specific properties that are truly broadly applicable (like DropShadow) - please file a separate issue on that with details on scenarios so we can prioritize. This thread appears to be too broad and contradictory to what Standard v1 is getting at.
