### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by tomakali** [Microsoft/xaml-standard#188]
Can microsoft include a drag and drop forms builder in windows
which users can use it to generate forms in C#/XAML and publish to azure
this will increase the user to gain knowledge of C#/XAML 

something like this
![ms-forms](https://cloud.githubusercontent.com/assets/5163951/26622953/c2269e7c-4609-11e7-804a-4f1a93e42eec.jpg)

**Comment by tomzorz** [comment]
@tomakali this is a tooling question, similar to #182 please post it on https://wpdev.uservoice.com

**Comment by Mike-EEE** [comment]
Would it be possible to consider not downvoting creative requests such as this from the community, please?  I am in agreement and understand that this doesn't adhere to the original/existing/current intent of the Xaml Standard, but if you look at the types of discussions that have sprung up here in the past month, we see:

- UI Controls (basically what Xaml Standard was intended to be focused on -- i.e. consolidation of common control vocabulary)
- Tooling
  - Serialization/Serializers (#145 is a good example 👼)
  - Design/Designers (this issue and others)

I believe we're in a potentially fragile (and no doubt painful) evolution of what's at play here.  We have a great deal of these types of conversations and requests occurring and it might be better to capture it here in another form here on GitHub (filtered from the designed/original intent of this initiative), rather to shoo it off to another disparate system with a fraction of the engagement power and value of the tooling we have available to us here.

Rather than discouraging/fragmenting contributions such as this, I feel it would better serve this repo (and community) to instead accurately tag and bag it under a different category, or even a different (child) repo altogether.  Otherwise, in order to accurately capture/analyze sentiment you are going to have to spend efforts in two disparate systems rather than one.

If we are not _at all_ concerned interested in capturing this type of information/sentiment, let's _all_ agree with that and move on as well.  In that case, we could point to another issue and definitively say "you know what?  We've already had a conversation about this and have all agreed that this is not what this is about and this is not wanted here."

That would absolutely suck and kill the project manager in me, however, LOL!

I concede I'm just some random opinionated dev however so I am certainly open to feedback on this, as always.  😄

**Comment by birbilis** [comment]
@ErickRock Judging from the titlebar shown in the image it's probably http://formoid.com/

**Comment by tomzorz** [comment]
@Mike-EEE I don't disagree, but I think everything has its place.

>  this doesn't adhere to the original/existing/current intent of the Xaml Standard

Exactly, that's why I think that there's a different place for this kind of feedback. IMHO this is not productive for the xaml-standard repository. There are certain already established places for tooling feedback, the wpdev uservoice is one of those. Obviously in the end it'll probably be Microsoft who decides what should be included in the discussion here and what isn't. As far as I see my position on the subject reflects theirs.

**Comment by harinikmsft** [comment]
As folks have already pointed out, this issue doesn't belong in this repo. XAML Standard is a vocabulary spec for standardizing common UI controls and APIs for C#/XAML developers targeting cross-platform UI development. 

Not denying that these are interesting topics and issues for the same set of developers, just that this is not the place where these can get addressed. You are welcome to continue this conversation here and link to it from [Visual Studio UWP tools uservoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/category/44115-uwp-wpf-xaml-tools) if you find the format here easier to have a discussion etc., 

I am marking this "rejected" and Closed to show that this kind of issue will not be addressed as part of the XAML Standard effort. 

P.S: Have you checked out [Windows Template Studio](https://github.com/Microsoft/WindowsTemplateStudio)? That might be a good repo to have this conversation as well. It is run by our friend, @crutkas!

**Comment by crutkas** [comment]
Kick up this thread over at [WTS](https://aka.ms/wts), it is actually much harder than you think to do what you're proposing due to what the framework someone is using under the hood.  Codebehind source code looks and acts differently than MVVMLight versus ...

We'd love to nerd out on this and see what is possible.
