### ISSUE TITLE
Rename BindableObject and BindableProperty

### ISSUE THREAD

**Issue by francedot** [Microsoft/xaml-standard#28]
- Rename BindableObject to DependencyObject.
- Rename BindableProperty to DependencyProperty as well as BindableProperty registration methods.

**Comment by atsushieno** [comment]
It should be the other way; "dependency" is bad name because it can mean different thing. "bindable" makes more sense.

**Comment by danielkatz** [comment]
@francedot I thinks the reason it was called DependecyProperty is because the effective value depends on multiple sources (animation, local template, etc.)

**Comment by birbilis** [comment]
Indeed DependencyXX was sounding strange to me when I first came across XAML

**Comment by francedot** [comment]
@atsushieno @danielkatz @birbilis I guess Dependency is a more general way to refer it and so a possible standardization. Isn't the Binding itself a Dependency between a source property on the DataContext and a Target Property in the View?

**Comment by atsushieno** [comment]
Naming is not like "general is better" but like "more precise is better" (otherwise we are going to name it "Object"). These things are used not when you want to "depend" on it but rather when you want to "bind" to something.

But hey, that's actually not my point. The disgusting point under this proposal is that "we want to force WPF-ness everywhere" kind of mindset does not respect other frameworks like Xamarin.Forms. What should occur first is to make sure that every framework users become happy to accept this standard without any harassing changes. "We are going to marry, so why don't YOU change your family name?" - it is by no means respectful.

How do we achieve mapping to the actual API? XAML is quite straightforward technology that relies on class names to be XML names (on elements or attributes). The existing XAML-based framework does not give any solution. We need to determine what's going to be achieved.

Until that happens, it is impossible for me to give any positive votes on this idea :-)

**Comment by Mike-EEE** [comment]
I would actually prefer to see Xaml break away from this altogether and be able to apply "bindings" or "dependencies" on _any_ object, thereby increasing its value and viability even further.

The only thing you do by couple your conceptual model with a base object is limit the application of your API.  While good for drawing boundaries, it does limit its application.

A good example is of course attached properties.  These are mimicked natively by the use of `ConditionalWeakTable`s but of course are not bindable in any way when being serialized/deserialized.  It would be great/valuable to do this with any POCO via Xaml's powerful serialization offerings and services.

**Comment by jassmith** [comment]
The naming for XAML Standard objects is not inherently derived from Xamarin.Forms names. Thus this issue is based off an incorrect premise. The naming for these particular properties in the XAML will be consistent with UWP.

**Comment by dotMorten** [comment]
I think this is a huge mistake. This seems to indicate that the codebehind will be completely disconnected from the XAML. These objects mentioned here are so central to XAML it should be considered part of the specification.

**Comment by lokitoth** [comment]
> The naming for these particular properties in the XAML will be consistent with UWP.

Do you guys have a proposal for dealing with this level of breaking change in WPF? Or is that no part of the XAML Standard track? (That's actually something important to know, because it would indicate more EOL signal for WPF)

**Comment by skendrot** [comment]
@lokitoth UWP naming of these (DependencyObject, DependencyProperty) are the same in WPF and UWP

**Comment by lokitoth** [comment]
@skendrot Good catch; I missed the "particular properties", and was thinking more about where UWP and WPF don't line up.
