### ISSUE TITLE
Add VirtualizingStackPanel control

### ISSUE THREAD

**Issue by wieslawsoltes** [Microsoft/xaml-standard#89]
Add VirtualizingStackPanel control
```XAML
<ListBox Items="{Binding}">
    <ListBox.ItemsPanel>
        <ItemsPanelTemplate>
            <VirtualizingStackPanel Orientation="Vertical"/>
        </ItemsPanelTemplate>
    </ListBox.ItemsPanel>
</ListBox>
```

**Comment by birbilis** [comment]
wonder if separate classes should be used for controls that support virtualization, or if most containers should support that by default and have some property to turn that behavior on/off

**Comment by birbilis** [comment]
Please also see
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/18327196-open-up-virtualizingpanel-and-orientedvirtualizing

and the discussion on being hard to implement Virtualizing controls in UWP here:
https://github.com/Microsoft/UWPCommunityToolkit/issues/1471#issuecomment-341431483

the issue seems to be that UWP uses sealed class for VirtualizingPanel, where WPF didn't
